const AppRoute = {
  ROOT: '/',
  SIGN_IN: '/auth/sign-in',
  SIGN_UP: '/auth/sign-up',
  CHECKOUT: '/checkout',
  ADMIN: '/admin/',
  ADMIN_DASHBOARD : '/admin/dashboard',
  ADMIN_PRODUCTS : '/admin/products',
  ADMIN_PRODUCTS_EDIT : "/admin/products/edit/:id",
  ADMIN_DRAFTS : '/admin/drafts',
  ADMIN_ADD_NEW_PRODUCT : '/admin/products/add-new-product',
  ADMIN_ORDERS : '/admin/orders',
  ADMIN_USERS : '/admin/users',
  ADMIN_USERINFO_PAGE : '/admin/users/user-info/:id',
  ADMIN_ORDERS_ORDER_INFO : '/admin/orders/order-info/:id',
  USER_DATA: '/dashboard',
  USER_PROFILE : '/dashboard/personal-data',
  USER_CART: '/dashboard/cart',
  USER_COMPARE: '/dashboard/compare-products',
  USER_ORDERS: '/dashboard/orders',
  USER_REVIEWS: '/dashboard/reviews',
  USER_REVIEWS_PUBLISHED : '/dashboard/reviews/published',
  USER_REVIEWS_PENDING : '/dashboard/reviews/pending',
  USER_FAVORITES: '/dashboard/favorites',
  USER_SCALES: '/dashboard/scales',
  CART: '/cart',
  CERTIFICATES: '/certificates',
  CERTIFICATE: '/certificates/:id/:title',
  PRODUCTS: '/products',
  PRODUCT: '/products/:id/:category/:collection/:title',
  NEW: '/products-new',
  SCALE: '/scale',
  FAVORITE: '/favorite',
  PUBLIC: '/public-agreement',
  PRIVACY: '/privacy-policy',
  USER_AGREEMENT: '/user-agreement',
  SUCCESS: '/auth/success',
  ORDER_SUCCESS : '/checkout/success',
} as const;

export type RoutePath = (typeof AppRoute)[keyof typeof AppRoute];

export { AppRoute };
